### ISSUE TITLE
为什么会多出来一列？

### ISSUE THREAD

**Issue by sunnyregion** [modood/table#1]
GoVersion : go1.9，windows下

我使用你的原例子，多出来一个空列

**Comment by modood** [comment]
@sunnyregion 可以详细描述一下吗，方便的话截个图

**Comment by sunnyregion** [comment]
就是你的源代码copy运行，就会多出一列，我自己的程序是有几列就额外多出几列。

**Comment by sunnyregion** [comment]
![1](https://user-images.githubusercontent.com/19296528/31010790-a1775416-a53e-11e7-8f0c-0e88bb498657.png)
![2](https://user-images.githubusercontent.com/19296528/31010791-a1c4f612-a53e-11e7-9954-fd7ff868576f.png)

**Comment by sunnyregion** [comment]
![3](https://user-images.githubusercontent.com/19296528/31010834-ca658d34-a53e-11e7-9286-a61115e07309.png)

**Comment by modood** [comment]
知道原因了，不是多了一列，是制表符宽度太大，导致每列之间的分隔竖线看起来都往左边凹进去了。因为字体或个人电脑设置的原因，制表符在 Windows 上显示的时候宽度无法控制。本项目后续版本可能会对此有所优化。

**Comment by modood** [comment]
最新提交（[59e3](https://github.com/modood/table/commit/59e3e0844114282b03996550e981760b772a4281)）新增了两个 API：
```
func OutputA(slice interface{})
func AsciiTable(slice interface{}) string
```
使用标准的 ascii 字符绘制表格，而不使用制表符。可以避免制表符宽度不一致引起的问题。
更多详情请查看 [README.md](https://github.com/modood/table#document)。

**Comment by sunnyregion** [comment]
谢谢，解决的很圆满。well done
